version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Europe/Ljubljana
      - TZ=Europe/Ljubljana
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
